# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: predict.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'predict.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpredict.proto\"3\n\x0ePredictRequest\x12\r\n\x05input\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\"5\n\x0fPredictResponse\x12\x0e\n\x06output\x18\x01 \x01(\t\x12\x12\n\nlatency_ms\x18\x02 \x01(\x01\"\x07\n\x05\x45mpty\"\x1d\n\x0cHealthStatus\x12\r\n\x05\x61live\x18\x01 \x01(\x08\x32\x63\n\x0ePredictService\x12.\n\x07Predict\x12\x0f.PredictRequest\x1a\x10.PredictResponse\"\x00\x12!\n\x06Health\x12\x06.Empty\x1a\r.HealthStatus\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predict_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=17
  _globals['_PREDICTREQUEST']._serialized_end=68
  _globals['_PREDICTRESPONSE']._serialized_start=70
  _globals['_PREDICTRESPONSE']._serialized_end=123
  _globals['_EMPTY']._serialized_start=125
  _globals['_EMPTY']._serialized_end=132
  _globals['_HEALTHSTATUS']._serialized_start=134
  _globals['_HEALTHSTATUS']._serialized_end=163
  _globals['_PREDICTSERVICE']._serialized_start=165
  _globals['_PREDICTSERVICE']._serialized_end=264
# @@protoc_insertion_point(module_scope)
